[twitter]
consumer_key = "CitBYZ4UlUibzhidmYf66U36G"
consumer_secret = "79ONIdiviJXBrSiFtbbZwUKGQUQMzCl2xNNixnCOQpOoXTkA1b"

[stripe]
api_key = "sk_test_51HSpP0EkhPBoRSztQiBMFo1YZODqiFmrIeBDV1XWi8KB2OFSniKlWUTBICfHV5kAFlXALU4NrTf1VfC876AoAez000ODzn5pz5"
subscription_link = "https://buy.stripe.com/test_8wMdU201u4nw3hC002"
